### PR TITLE
added php 8 support

### PR DESCRIPTION
**Pull request by StanBarrows**

### CODE REVIEW

**Comment by StanBarrows** [comment]
@CasperLaiTW

Sorry. I've somehow messed something up with your permission. I've sent you an admin invite again.

I've also updated PHP 8.0 support.

Cheers
Sebastian

**Review by wireless25 — COMMENTED** [review]
looks good

**Review by wireless25 — APPROVED** [review]
looks good

**Review by wireless25 — APPROVED** [review]

**Comment by CasperLaiTW** [comment]
easy!

**Pull request merged**
