### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by StanBarrows**

### CODE REVIEW

**Comment by StanBarrows** [comment]
@CasperLaiTW  There were some unrelated history conflicts with the master branch. I think i've accidentally removed your .composer updates. can you add them again?

**Comment by CasperLaiTW** [comment]
sure, let me update it.

**Review by CasperLaiTW — APPROVED** [review]
Github actions passed

**Comment by CasperLaiTW** [comment]
I will do new branch to merge, I think GithubActions branch was mess up.

**Pull request closed without merging**
